
substitutions:
  _REGION: us-central1
  _AR_REPO: matchaauto
  _IMAGE_NAME: backend
  _SERVICE_NAME: matchaauto-api-staging
  _MIGRATE_JOB_NAME: matchaauto-migrate-staging
  _RUN_SA: matchaauto-run-sa
  _INSTANCE_CONNECTION_NAME: 'PROJECT_ID:REGION:INSTANCE' # UPDATE THIS

steps:
  # 1. Build the production image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    args: 
      - 'build'
      - '-f'
      - 'backend/Dockerfile.production'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:$SHORT_SHA'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:latest'
      - '.'

  # 2. Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push'
    args: 
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:$SHORT_SHA'

  # 3. Update Migration Job
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'update-migrate-job'
    entrypoint: gcloud
    args:
      - 'run'
      - 'jobs'
      - 'update'
      - '${_MIGRATE_JOB_NAME}'
      - '--region'
      - '${_REGION}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:$SHORT_SHA'
      - '--add-cloudsql-instances'
      - '${_INSTANCE_CONNECTION_NAME}'
      - '--set-secrets'
      - 'DATABASE_URL=DATABASE_URL:latest'
      - '--set-env-vars'
      - 'NODE_ENV=production,APP_ENV=staging'

  # 4. Execute Migration Job (Wait for success)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'run-migrations'
    entrypoint: gcloud
    args:
      - 'run'
      - 'jobs'
      - 'execute'
      - '${_MIGRATE_JOB_NAME}'
      - '--region'
      - '${_REGION}'
      - '--wait'

  # 5. Deploy Service to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-service'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--region'
      - '${_REGION}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:$SHORT_SHA'
      - '--service-account'
      - '${_RUN_SA}@$PROJECT_ID.iam.gserviceaccount.com'
      - '--add-cloudsql-instances'
      - '${_INSTANCE_CONNECTION_NAME}'
      - '--allow-unauthenticated'
      # Secrets mapping (Security: Passwords are in DATABASE_URL secret)
      - '--set-secrets'
      - 'DATABASE_URL=DATABASE_URL:latest,CLERK_SECRET_KEY=CLERK_SECRET_KEY:latest,MERCADO_PAGO_ACCESS_TOKEN=MERCADO_PAGO_ACCESS_TOKEN:latest,PAYPAL_CLIENT_ID=PAYPAL_CLIENT_ID:latest,PAYPAL_CLIENT_SECRET=PAYPAL_CLIENT_SECRET:latest,PAYPAL_WEBHOOK_ID=PAYPAL_WEBHOOK_ID:latest,ADMIN_USER_IDS=ADMIN_USER_IDS:latest'
      # Env vars (Security: NO DB_PASS here, NO fixed PORT)
      - '--set-env-vars'
      - 'NODE_ENV=production,APP_ENV=staging,PAYPAL_ENV=sandbox,CORS_ALLOW_ORIGINS=https://www.match-autos.com'

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:$SHORT_SHA'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:latest'

options:
  logging: CLOUD_LOGGING
